import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {blankProject,entity,quantities,materialFor} from '../shared/model.js';
import {initKernel,toSolid} from '../shared/solid-kernel.js';
import {sweepProfile} from '../shared/sweep.js';
import {EditorEngine} from '../frontend/engine.js';
import {useEditor} from '../frontend/store.js';
import {objectGeometry,objectMatrix} from '../shared/geometry.js';
import {geminiConfig,reserveDemo,generateFurniturePlan,verifyGeminiKeys} from '../shared/gemini-furniture.js';
await initKernel();
test('Follow Me uses the full drawn rectangle on XY, XZ and YZ',()=>{
 for(const thinAxis of [0,1,2]){const size=[10,20,30];size[thinAxis]=0.1;const profile=entity({isFace:true,thinAxis,size,position:[0,0,0]});const result=sweepProfile(profile,[entity({kind:'line',size:[1,1,1],position:[0,0,0],points:[[0,0,0],[0,0,100]]})]);const solid=toSolid(result);assert.ok(Math.abs(solid.volume()-size.filter((_,i)=>i!==thinAxis).reduce((a,b)=>a*b)*100)<0.01);solid.delete();}
});
test('solid operations replace input objects atomically, preserve nested groups and undo',async()=>{
 for(const operation of ['union','subtract','intersect','trim','split','outer-shell']){const p=blankProject();p.groups=[{id:'parent',name:'Parent'},{id:'child',parentId:'parent',name:'Child'}];p.objects=[entity({groupId:'child',size:[100,100,100],position:[0,0,0]}),entity({size:[100,100,100],position:[50,0,0]})];useEditor.getState().set({engine:null});useEditor.getState().load(p);useEditor.getState().set({selection:p.objects.map(o=>o.id)});await EditorEngine.prototype.solidOperation.call({},operation);const s=useEditor.getState();assert.equal(s.project.objects.length,operation==='split'?3:operation==='trim'?2:1);assert.ok(!s.project.objects.some(o=>o.id===p.objects[0].id));assert.ok(s.project.groups.some(g=>g.id==='parent'));s.undo();assert.deepEqual(useEditor.getState().project.objects,p.objects);}
});
test('custom colours apply to selected objects and individual faces and survive undo',()=>{
 const p=blankProject();p.objects=[entity()];p.materials=[{id:'blue-demo',name:'Blue',color:'#245ee8',roughness:0.5}];useEditor.getState().load(p);useEditor.getState().set({selection:[p.objects[0].id],face:null});useEditor.getState().applyMaterial('blue-demo');assert.equal(useEditor.getState().project.objects[0].material,'blue-demo');useEditor.getState().set({face:{index:2}});useEditor.getState().applyMaterial('sage');assert.equal(useEditor.getState().project.objects[0].faceMaterials[2],'sage');assert.equal(materialFor(useEditor.getState().project,'blue-demo').color,'#245ee8');useEditor.getState().undo();assert.equal(useEditor.getState().project.objects[0].faceMaterials[2],undefined);
});
test('rectangle snaps to elevated corners and stays on that plane after first click',()=>{
 const p=blankProject();const o=entity({size:[1000,500,18],position:[0,0,809]});p.objects=[o];useEditor.getState().load(p);useEditor.getState().set({tool:'rectangle',plane:'XY',axis:null,snapEnabled:true});const e=Object.create(EditorEngine.prototype);e.points=[];e.objects=new Map();const m=new T.Mesh(objectGeometry(o),new T.MeshBasicMaterial({side:T.DoubleSide}));m.applyMatrix4(objectMatrix(o));m.updateMatrixWorld();m.userData.id=o.id;e.objects.set(o.id,m);e.camera=new T.PerspectiveCamera(45,4/3,1,100000);e.camera.position.set(3000,-4000,4000);e.camera.up.set(0,0,1);e.camera.lookAt(0,0,800);e.camera.updateMatrixWorld();e.ray=new T.Raycaster();e.mouse=new T.Vector2();e.renderer={domElement:{getBoundingClientRect:()=>({left:0,top:0,width:800,height:600})}};const screen=p=>{const q=p.clone().project(e.camera);return {clientX:(q.x+1)*400,clientY:(1-q.y)*300};};const corner=new T.Vector3(500,-250,818);const hit=e.workPoint(screen(corner));assert.ok(hit.point.distanceTo(corner)<1e-6);e.points=[hit.point];const next=e.workPoint(screen(new T.Vector3(100,100,818)));assert.equal(next.point.z,818);
});
test('Gemini verifies key metadata without generating tokens',async()=>{const result=await verifyGeminiKeys({GEMINI_API_KEY_1:'test'},async(url)=>{assert.ok(!url.includes('generateContent'));return Response.json({inputTokenLimit:1048576,outputTokenLimit:65536});});assert.equal(result.keys[0].valid,true);assert.equal(result.billingVerified,false);});
test('Gemini free-tier gate, persistent shared caps and key deduplication',async()=>{assert.equal(geminiConfig({GEMINI_API_KEY_1:'same',GEMINI_API_KEY_2:'same'}).keys.length,1);await assert.rejects(generateFurniturePlan({GEMINI_API_KEY_1:'test'},'wardrobe',{}),/Free tier/);let l=reserveDemo({},1000);l=reserveDemo(l,2000);assert.throws(()=>reserveDemo(l,3000),/cap/);assert.equal(reserveDemo(l,65000).attempts,3);});
test('Gemini falls back on invalid credentials, records tokens, but stops on quota',async()=>{const env={GEMINI_API_KEY_1:'a',GEMINI_API_KEY_2:'b',GEMINI_FREE_TIER_CONFIRMED:'true'};let calls=0,reservations=0,recorded;const result=await generateFurniturePlan(env,'Build wardrobe',{reserve:async()=>reservations++,record:async u=>recorded=u,fetcher:async()=>++calls===1?new Response('',{status:403}):Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({type:'wardrobe',width:1800,depth:600,height:2400})}]}}],usageMetadata:{promptTokenCount:200,candidatesTokenCount:80,totalTokenCount:280}})});assert.equal(result.usage.slot,2);assert.equal(recorded.totalTokens,280);assert.equal(reservations,2);calls=0;await assert.rejects(generateFurniturePlan(env,'Build wardrobe',{reserve:async()=>{},record:async()=>{},fetcher:async()=>{calls++;return new Response('',{status:429});}}),/quota/);assert.equal(calls,1);});
